#
# This file is part of gruvi. Gruvi is free software available under the
# terms of the MIT license. See the file "LICENSE" that was provided
# together with this source file for the licensing terms.
#
# Copyright (c) 2012-2013 the gruvi authors. See the file "AUTHORS" for a
# complete list.

from __future__ import absolute_import, print_function

import os
import sys
import textwrap
import json
import time
import re

from setuptools import setup, Extension

# CFFI is needed to call setup() and therefore it needs to be installed before
# this setup script can be run. Look in the version history for this file for a
# hack to install it automatically. However for now let's keep it simple and
# just require the user to install it.

try:
    import cffi
except ImportError:
    sys.stderr.write('Error: CFFI (required for setup) is not available.\n')
    sys.stderr.write('Please use "pip install cffi", or equivalent.\n')
    sys.exit(1)

re_int = re.compile('^(\d*).*$')
cffi_ver = tuple((int(re_int.sub('0\\1', x)) for x in cffi.__version__.split('.')))
if cffi_ver < (0, 8):
    sys.stderr.write('Error: CFFI (required for setup) is too old.\n')
    sys.stderr.write('Please install at least version 0.8.\n')
    sys.exit(1)


version_info = {
    'name': 'gruvi',
    'version': '0.10.2.dev',
    'description': 'Synchronous evented IO with pyuv and fibers',
    'author': 'Geert Jansen',
    'author_email': 'geertj@gmail.com',
    'url': 'https://github.com/geertj/gruvi',
    'license': 'MIT',
    'classifiers': [
        'Development Status :: 4 - Beta',
        'License :: OSI Approved :: MIT License',
        'Operating System :: POSIX',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: MacOS :: MacOS X',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4'
    ]
}

topdir, _ = os.path.split(os.path.abspath(__file__))


def update_version():
    """Update the _version.py file."""
    fname = os.path.join('.', 'gruvi', '_version.py')
    try:
        with open(fname) as fin:
            current = fin.read()
    except IOError:
        current = None
    # json.dumps will produce valid Python for version_info
    new = textwrap.dedent("""\
            # This file is autogenerated. Do not edit.
            version_info = {0}
            """).format(json.dumps(version_info, indent=4, sort_keys=True,
                                   separators=(',', ': ')))
    if current == new:
        return
    tmpname = '{0}.{1}-tmp'.format(fname, os.getpid())
    with open(tmpname, 'w') as fout:
        fout.write(new)
    os.rename(tmpname, fname)
    print('Updated _version.py')


def main():
    os.chdir(topdir)
    update_version()
    # Import the FFI modules without importing the package.
    sys.path.append('gruvi')
    try:
        import http_ffi
        import jsonrpc_ffi
    except cffi.VerificationError:
        if not sys.platform.startswith('win'):
            raise
        # On my Windows 7 system, the first build reproducably results in a
        # link.exe error 1104. There multiple reports on the Internet of people
        # running into this. It is caused by /some/ process locking an
        # executable file (here a .pyd file created by CFFI). Different people
        # reported success disabling different programs like a virus scanner
        # but none of those worked for me. However, it appears that if we just
        # try again importing the ffi modules that things *do* work. So just do
        # that.
        # The sleep() below isn't really necessary for me but since I don't
        # know which program is locking the file I put it in just in case there
        # is a race condition that for some reason I am not triggering.
        print('Enabling workaround for link.exe error 1104')
        time.sleep(1)
        import http_ffi
        import jsonrpc_ffi
    sys.path.pop()
    ext_modules = [http_ffi.ffi.verifier.get_extension(),
                   jsonrpc_ffi.ffi.verifier.get_extension()]
    # Note that on Windows it's more involved to compile _sslcompat because
    # there's no system provided OpenSSL and you need to match the version that
    # was used to compile your Python.
    if sys.version_info[:2] < (3, 5):
        ext_modules.append(Extension('_sslcompat', ['gruvi/_sslcompat.c'],
                                     libraries=['ssl', 'crypto']))
    setup(
        packages=['gruvi', 'gruvi.txdbus'],
        install_requires=['cffi', 'fibers', 'pyuv', 'six'],
        ext_package='gruvi',
        ext_modules=ext_modules,
        **version_info
    )


if __name__ == '__main__':
    main()
